#include "c_emitter.h"
#include <set>
#include <sstream>

namespace {

std::string mangle(const std::string &name) { return "ps_" + name; }

void collectVars(const std::vector<Stmt *> &stmts, std::set<std::string> &out) {
    for (Stmt *s : stmts) {
        std::visit([&](auto &&node) {
            using T = std::decay_t<decltype(node)>;
            if constexpr (std::is_same_v<T, SetStmt>) out.insert(node.name);
            else if constexpr (std::is_same_v<T, AddStmt>) out.insert(node.varName);
            else if constexpr (std::is_same_v<T, RepeatStmt>) collectVars(node.body, out);
            else if constexpr (std::is_same_v<T, IfStmt>) collectVars(node.thenBody, out);
        }, s->node);
    }
}

std::string emitExpr(const Expr *e) {
    return std::visit([&](auto &&node) -> std::string {
        using T = std::decay_t<decltype(node)>;
        if constexpr (std::is_same_v<T, IntLit>) {
            return "ps_int(" + std::to_string(node.value) + "L)";
        } else if constexpr (std::is_same_v<T, StringLit>) {
            std::string escaped;
            for (char c : node.value) {
                if (c == '"' || c == '\\') escaped += '\\';
                if (c == '\n') { escaped += "\\n"; continue; }
                escaped += c;
            }
            return "ps_str(\"" + escaped + "\")";
        } else if constexpr (std::is_same_v<T, VarRef>) {
            return mangle(node.name);
        } else if constexpr (std::is_same_v<T, BinaryExpr>) {
            const char *fn = node.op == BinOp::Add ? "ps_add"
                            : node.op == BinOp::Gt  ? "ps_gt"
                            : node.op == BinOp::Lt  ? "ps_lt"
                                                     : "ps_eq";
            return std::string(fn) + "(" + emitExpr(node.lhs) + ", " + emitExpr(node.rhs) + ")";
        }
    }, e->node);
}

void emitStmt(const Stmt *s, std::ostream &out, std::string indent, int &loopCounter) {
    std::visit([&](auto &&node) {
        using T = std::decay_t<decltype(node)>;
        if constexpr (std::is_same_v<T, SayStmt>) {
            out << indent << "ps_say(" << emitExpr(node.expr) << ");\n";
        } else if constexpr (std::is_same_v<T, SetStmt>) {
            out << indent << mangle(node.name) << " = " << emitExpr(node.expr) << ";\n";
        } else if constexpr (std::is_same_v<T, AddStmt>) {
            out << indent << mangle(node.varName) << " = ps_add(" << mangle(node.varName)
                << ", " << emitExpr(node.expr) << ");\n";
        } else if constexpr (std::is_same_v<T, RepeatStmt>) {
            std::string i = "ps__i" + std::to_string(loopCounter);
            std::string n = "ps__n" + std::to_string(loopCounter);
            loopCounter++;
            out << indent << "{\n";
            out << indent << "    long " << n << " = ps_as_int(" << emitExpr(node.count) << ");\n";
            out << indent << "    for (long " << i << " = 0; " << i << " < " << n << "; " << i << "++) {\n";
            for (Stmt *inner : node.body) emitStmt(inner, out, indent + "        ", loopCounter);
            out << indent << "    }\n";
            out << indent << "}\n";
        } else if constexpr (std::is_same_v<T, IfStmt>) {
            out << indent << "if (ps_truthy(" << emitExpr(node.cond) << ")) {\n";
            for (Stmt *inner : node.thenBody) emitStmt(inner, out, indent + "    ", loopCounter);
            out << indent << "}\n";
        }
    }, s->node);
}

} // namespace

std::string emitProgram(const std::vector<Stmt *> &program) {
    std::set<std::string> vars;
    collectVars(program, vars);

    std::ostringstream out;
    out << "/* generated by plainspeak — do not edit by hand */\n";
    out << "#include \"plainspeak_runtime.h\"\n\n";
    out << "int main(void) {\n";
    for (const auto &v : vars) out << "    PsValue " << mangle(v) << ";\n";
    if (!vars.empty()) out << "\n";

    int loopCounter = 0;
    for (Stmt *s : program) emitStmt(s, out, "    ", loopCounter);

    out << "    return 0;\n";
    out << "}\n";
    return out.str();
}
